language: node_js

node_js:
  - "4"
  - "6"

notifications:
  email: false

env:
  global:
    # GH_TOKEN
    - secure: "P0ksGaQg9x2OA2+Ue7M8DRMNBS1RrMK4pi5vV4HeGlTDNoZvWhMbmb5RwtykXBR12H8BTzrnsxA5BfMzzVh+F/88eoSL5WJV7n/Ea39xxiATA2edBjbpCFSsAHI8JQWTT0uo2dD5XeLWAx2ZTELRX2PVr6dn7yeJ2PlF39HXXqzi7QeZ+FlHX5dHckrx+9MX9/+qBKzLZegeQHUDgYs7SxFDJ+IshYVY6SMF+fvy7JIVIcQhAZzlyYADaraHmluGuFuNVmfRDOVaDSJX+WQoGfo7UrQawY4hDZRZzXcIBXJSczJJ+JPBXuDDUKznvVifsHR96dxQrOUdyRF3zjRSW3CxFm58loTecsekV1s0f88K0tYfjjreUh5qoPWI2bue5Mqk8AC7hkkWRvOQX9XRrlfzqz5wEWTYIzU44Nv4NzkuBjtgQUMnA7WuMiwjngjGLwHVJfw7TuliYca089xtX6ZocUUXwB834vh2sLIIn/dPLYovOEsWkgav8uzHpizSZwap/gpchbUnIrUeahFjyfr1g5xbzyqkodCe5UhSGjI7OcPbS4WH8/pE7z4Vuz2ZMYcKsdCfyeorzaZ24ERGXQEVA+gA9rWtUM9gyPqdkq2btq75Xxy2lP7HsyA6D637q9Qmn86jgNItVSaFjTaS9AobzaDC8bMDvDV7N6rHLuQ="
    - GIT_DEPLOY_REPO=https://$GH_TOKEN@github.com/PierrickP/number26.git

deploy:
  - provider: script
    script: npm run deployDocs
    skip_cleanup: true
    on:
      branch: master
  - provider: npm
    email: "mulotmail@gmail.com"
    api_key:
      secure: FPj38o+Rvpk/f/0MUNLSYztg4rfOAWJqtpFeAL5Ebp7DZqFGRRzK+EzEq3knecoRyV9zqMw52LY1bZgvXv8zLN8Htfq5836sftltUWTYdDgeMkUq5yDz4XO1gCeNdb+n0byf2CE7dk1KKYzUIOmd+ZGqM3dCcrgooh3hj+1SoCpXReXVa4iVPUNBra0dGBfQH5esB8OlUe6NhOJ9b7fDS3nfTEvT2tiNR8iLM6qvKhwWIv2udXh5W8JMVJx4BJm5Wp0rr+wjSSeutPSGITF4pfz6b0/YlE5DvfOJU7oGxKB58yXLfNb1XDW9zy5/0nr9aH/OYxVn3lKKmkZ+7KQxIaZamJVfn1mTDM4XBjhnzMWcrmcIoogtK9GMjQjmdHqAo+/tNHfEvdtfCAEvM+r6unauEsRtvIYLXg3cqv1oDY0W2rcyWu9cNW+caUbcJqlY5xJF21saEj7kS25T77yUcvvQ6QCW7xmyFd5cy7BYPl5F3os+yj+yrPslt+90cr2RaeX0GG7mi1OroyWa2xHfbRcADYTslHuYqdOt8V70o9D2M1Q9gvM8szRcfds0Rrw4rG05I3/AnjZIS49jYYhDyoBN5RGO9NBc4jV5t/+VvY0koClFcX/7evUVvhkrddFero3V38i55RIk8TgPzpddoxXKc7wLMb/t6g3rqJ/j/J4=
    skip_cleanup: true
    on:
      branch: master
